const ActionTypes = {
  NAVIGATE_TO: 'NAVIGATE_TO',
  GET_USER_INFO: 'GET_USER_INFO',
  GET_USER_INFO_SUCCESS: 'GET_USER_INFO_SUCCESS',
  GET_USER_INFO_FAIL: 'GET_USER_INFO_FAIL',
  GET_USER_INFO_LOGOUT: 'GET_USER_INFO_LOGOUT',
};

export default ActionTypes;
